# Generated by Django 3.2.9 on 2022-01-21 02:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('name', models.CharField(max_length=100, verbose_name='Names')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_referencial', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Image Referencial')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of Category')),
                ('image_referencial', models.ImageField(upload_to='category/', verbose_name='Image Referencial')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Social media',
                'verbose_name_plural': 'Social medias',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptors',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('contact_us', models.TextField(verbose_name='Contact us')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date created')),
                ('date_of_change', models.DateField(auto_now=True, verbose_name='Date modified')),
                ('date_deleted', models.DateField(auto_now=True, verbose_name='Date eliminated ')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Title of post')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField()),
                ('image_referencial', models.ImageField(max_length=255, upload_to='images/', verbose_name='Referencial Image')),
                ('published', models.BooleanField(default=False, verbose_name='Publish / No Publish')),
                ('date_published', models.DateField(verbose_name='Date of publish')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
